Repository dnd-side-project/dnd-12th-8-backend, pull requests merged in 2025-02, with the labels that each got.

#2 MongoDB 설정 추가
  .gitignore
  build.gradle
  src/main/java/com/dnd/demo/common/Test.java
  src/main/java/com/dnd/demo/common/TestController.java
  src/main/java/com/dnd/demo/common/TestRepository.java
  src/main/resources/application.properties
Labels: enhancement

#1 Feat : 기본 엔티티 생성 및 JPA 의존성 추가
  build.gradle
  settings.gradle
  src/main/java/com/dnd/demo/common/entity/BaseEntity.java
  src/main/java/com/dnd/demo/domain/Quiz/entity/Quiz.java
  src/main/java/com/dnd/demo/domain/Quiz/entity/QuizOption.java
  src/main/java/com/dnd/demo/domain/Quiz/entity/QuizOptionKey.java
  src/main/java/com/dnd/demo/domain/Quiz/entity/QuizResult.java
  src/main/java/com/dnd/demo/domain/member/entity/Comment.java
  src/main/java/com/dnd/demo/domain/member/entity/Favorite.java
  src/main/java/com/dnd/demo/domain/member/entity/Member.java
  src/main/java/com/dnd/demo/domain/project/entity/Advertisement.java
  src/main/java/com/dnd/demo/domain/project/entity/Category.java
  src/main/java/com/dnd/demo/domain/project/entity/Job.java
  src/main/java/com/dnd/demo/domain/project/entity/Level.java
  src/main/java/com/dnd/demo/domain/project/entity/Project.java
  src/main/java/com/dnd/demo/domain/project/entity/ProjectCategory.java
  src/main/java/com/dnd/demo/domain/project/entity/ProjectDetail.java
  src/main/java/com/dnd/demo/domain/project/entity/ProjectDetailKey.java
Labels: enhancement

#4 CI, CD 구축
  .github/workflows/cd-deploy.yml
  .github/workflows/ci-test.yml
  gradlew
  src/test/java/com/dnd/demo/DemoApplicationTests.java
Labels: enhancement

#9 프로젝트 생성 초안 구현
  build.gradle
  src/main/java/com/dnd/demo/domain/Quiz/dto/request/QuizRequest.java
  src/main/java/com/dnd/demo/domain/Quiz/entity/Quiz.java
  src/main/java/com/dnd/demo/domain/Quiz/entity/QuizOption.java
  src/main/java/com/dnd/demo/domain/Quiz/entity/QuizOptionKey.java
  src/main/java/com/dnd/demo/domain/Quiz/repository/QuizOptionRepository.java
  src/main/java/com/dnd/demo/domain/Quiz/repository/QuizRepository.java
  src/main/java/com/dnd/demo/domain/Quiz/service/QuizOptionService.java
  src/main/java/com/dnd/demo/domain/Quiz/service/QuizService.java
  src/main/java/com/dnd/demo/domain/feedback/dto/request/FeedbackFormRequest.java
  src/main/java/com/dnd/demo/domain/feedback/entity/FeedbackAnswer.java
  src/main/java/com/dnd/demo/domain/feedback/entity/FeedbackForm.java
  src/main/java/com/dnd/demo/domain/feedback/entity/FeedbackQuestion.java
  src/main/java/com/dnd/demo/domain/feedback/entity/FeedbackResponse.java
  src/main/java/com/dnd/demo/domain/feedback/repository/FeedbackFormRepository.java
  src/main/java/com/dnd/demo/domain/feedback/service/FeedbackFormService.java
  src/main/java/com/dnd/demo/domain/member/dto/CommentDto.java
  src/main/java/com/dnd/demo/domain/member/entity/Member.java
  src/main/java/com/dnd/demo/domain/member/entity/MemberCategory.java
  src/main/java/com/dnd/demo/domain/member/repository/MemberRepository.java
  src/main/java/com/dnd/demo/domain/member/service/CommentQueryDslRepositoryImpl.java
  src/main/java/com/dnd/demo/domain/member/service/MemberService.java
  src/main/java/com/dnd/demo/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/dnd/demo/domain/project/controller/ProjectController.java
  src/main/java/com/dnd/demo/domain/project/dto/request/PlatformCategoryRequest.java
  src/main/java/com/dnd/demo/domain/project/dto/request/ProjectCreateRequest.java
  src/main/java/com/dnd/demo/domain/project/dto/request/ProjectDetailRequest.java
  src/main/java/com/dnd/demo/domain/project/dto/request/ProjectSaveRequest.java
  src/main/java/com/dnd/demo/domain/project/dto/request/TemporaryProjectCreateRequest.java
  src/main/java/com/dnd/demo/domain/project/entity/Category.java
  src/main/java/com/dnd/demo/domain/project/entity/Job.java
  src/main/java/com/dnd/demo/domain/project/entity/Level.java
  src/main/java/com/dnd/demo/domain/project/entity/Project.java
  src/main/java/com/dnd/demo/domain/project/entity/ProjectCategory.java
  src/main/java/com/dnd/demo/domain/project/entity/ProjectDetail.java
  src/main/java/com/dnd/demo/domain/project/enums/DetailType.java
  src/main/java/com/dnd/demo/domain/project/enums/Job.java
  src/main/java/com/dnd/demo/domain/project/enums/Level.java
  src/main/java/com/dnd/demo/domain/project/enums/PlatformType.java
  src/main/java/com/dnd/demo/domain/project/enums/ProjectStatus.java
  src/main/java/com/dnd/demo/domain/project/enums/QuestionType.java
  src/main/java/com/dnd/demo/domain/project/repository/CategoryRepository.java
  src/main/java/com/dnd/demo/domain/project/repository/ProjectCategoryRepository.java
  src/main/java/com/dnd/demo/domain/project/repository/ProjectDetailRepository.java
  src/main/java/com/dnd/demo/domain/project/repository/ProjectRepository.java
  src/main/java/com/dnd/demo/domain/project/service/CategoryService.java
  src/main/java/com/dnd/demo/domain/project/service/ProjectCategoryService.java
  src/main/java/com/dnd/demo/domain/project/service/ProjectDetailService.java
  src/main/java/com/dnd/demo/domain/project/service/ProjectService.java
  src/main/java/com/dnd/demo/global/auth/config/SecurityConfig.java
  src/main/java/com/dnd/demo/global/auth/dto/OAuthUserDetails.java
  src/main/java/com/dnd/demo/global/exception/CustomErrorResponse.java
  src/main/java/com/dnd/demo/global/exception/CustomException.java
  src/main/java/com/dnd/demo/global/exception/ErrorCode.java
  src/main/java/com/dnd/demo/global/exception/GlobalExceptionHandler/GlobalExceptionHandler.java
Labels: enhancement

#16 프로젝트 상세 조회, 삭제 api 추가
  src/main/java/com/dnd/demo/domain/Quiz/dto/response/QuizResponse.java
  src/main/java/com/dnd/demo/domain/Quiz/repository/QuizOptionRepository.java
  src/main/java/com/dnd/demo/domain/Quiz/repository/QuizRepository.java
  src/main/java/com/dnd/demo/domain/Quiz/service/QuizOptionService.java
  src/main/java/com/dnd/demo/domain/Quiz/service/QuizService.java
  src/main/java/com/dnd/demo/domain/feedback/dto/response/FeedbackFormResponse.java
  src/main/java/com/dnd/demo/domain/feedback/repository/FeedbackFormRepository.java
  src/main/java/com/dnd/demo/domain/feedback/service/FeedbackFormService.java
  src/main/java/com/dnd/demo/domain/project/controller/ProjectController.java
  src/main/java/com/dnd/demo/domain/project/dto/response/PlatformCategoryResponse.java
  src/main/java/com/dnd/demo/domain/project/dto/response/ProjectDetailResponse.java
  src/main/java/com/dnd/demo/domain/project/dto/response/ProjectResponseDto.java
  src/main/java/com/dnd/demo/domain/project/repository/CategoryRepository.java
  src/main/java/com/dnd/demo/domain/project/repository/ProjectDetailRepository.java
  src/main/java/com/dnd/demo/domain/project/repository/ProjectQueryDslRepository.java
  src/main/java/com/dnd/demo/domain/project/repository/ProjectQueryDslRepositoryImpl.java
  src/main/java/com/dnd/demo/domain/project/service/CategoryService.java
  src/main/java/com/dnd/demo/domain/project/service/ProjectCategoryService.java
  src/main/java/com/dnd/demo/domain/project/service/ProjectDetailService.java
  src/main/java/com/dnd/demo/domain/project/service/ProjectService.java
  src/main/java/com/dnd/demo/global/exception/ErrorCode.java
Labels: documentation

#18 이미지 Presigned URL 반환 api 구현
  build.gradle
  src/main/java/com/dnd/demo/domain/image/S3CleanupBatch.java
  src/main/java/com/dnd/demo/domain/image/controller/AwsS3Controller.java
  src/main/java/com/dnd/demo/domain/image/dto/response/PresignedUrlResponse.java
  src/main/java/com/dnd/demo/domain/image/service/AwsS3Service.java
  src/main/java/com/dnd/demo/domain/project/enums/DetailType.java
  src/main/java/com/dnd/demo/domain/project/repository/ProjectDetailRepository.java
  src/main/java/com/dnd/demo/global/common/TestController.java
  src/main/java/com/dnd/demo/global/common/config/AwsS3Config.java
  src/main/java/com/dnd/demo/global/exception/ErrorCode.java
Labels: enhancement

#19 마이페이지 임시 프로젝트 상세 조회(생성자) / 피드백 폼 상세 조회(응답자) api 구현
  src/main/java/com/dnd/demo/domain/feedback/controller/FeedbackFormController.java
  src/main/java/com/dnd/demo/domain/mypage/controller/MyPageController.java
  src/main/java/com/dnd/demo/domain/mypage/dto/MyPageProjectDetailResponseDto.java
  src/main/java/com/dnd/demo/domain/mypage/service/MyPageService.java
  src/main/java/com/dnd/demo/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/dnd/demo/domain/project/repository/ProjectRepository.java
  src/main/java/com/dnd/demo/global/exception/ErrorCode.java
Labels: enhancement

#21 OPEN 상태인 프로젝트 validate 검사 추가
  src/main/java/com/dnd/demo/domain/Quiz/service/QuizService.java
  src/main/java/com/dnd/demo/domain/feedback/service/FeedbackFormService.java
  src/main/java/com/dnd/demo/global/exception/ErrorCode.java
Labels: enhancement

#23 내 정보 조회, 온보딩 정보 입력 api 구현
  src/main/java/com/dnd/demo/domain/member/controller/MemberController.java
  src/main/java/com/dnd/demo/domain/member/dto/request/OnboardingRequest.java
  src/main/java/com/dnd/demo/domain/member/dto/response/MemberResponse.java
  src/main/java/com/dnd/demo/domain/member/entity/Member.java
  src/main/java/com/dnd/demo/domain/member/entity/MemberCategory.java
  src/main/java/com/dnd/demo/domain/member/repository/MemberCategoryRepository.java
  src/main/java/com/dnd/demo/domain/member/service/MemberService.java
  src/main/java/com/dnd/demo/domain/project/repository/CategoryQueryDslRepository.java
  src/main/java/com/dnd/demo/domain/project/repository/CategoryQueryDslRepositoryImpl.java
  src/main/java/com/dnd/demo/domain/project/repository/ProjectQueryDslRepositoryImpl.java
  src/main/java/com/dnd/demo/global/auth/config/SecurityConfig.java
  src/main/java/com/dnd/demo/global/auth/handler/OAuthSuccessHandler.java
  src/main/resources/static/dashboard.html
  src/main/resources/static/onboarding.html
Labels: enhancement

#25 카카오 로그인 SpringSecurity OAuth2 자동 사용 방식에서 수동 방식으로 변경
  build.gradle
  src/main/java/com/dnd/demo/domain/oauth/constants/OAuthConstant.java
  src/main/java/com/dnd/demo/domain/oauth/controller/KakaoLoginPageController.java
  src/main/java/com/dnd/demo/domain/oauth/controller/OAuthController.java
  src/main/java/com/dnd/demo/domain/oauth/domain/oauth/OAuthClient.java
  src/main/java/com/dnd/demo/domain/oauth/domain/oauth/OAuthLoginParams.java
  src/main/java/com/dnd/demo/domain/oauth/domain/oauth/OAuthProvider.java
  src/main/java/com/dnd/demo/domain/oauth/domain/oauth/OAuthUserInfo.java
  src/main/java/com/dnd/demo/domain/oauth/dto/response/TokenResponse.java
  src/main/java/com/dnd/demo/domain/oauth/infrastructure/kakao/KaKaoApiClient.java
  src/main/java/com/dnd/demo/domain/oauth/infrastructure/kakao/KaKaoToken.java
  src/main/java/com/dnd/demo/domain/oauth/infrastructure/kakao/KaKaoUserInfo.java
  src/main/java/com/dnd/demo/domain/oauth/infrastructure/kakao/KakaoLoginParam.java
  src/main/java/com/dnd/demo/domain/oauth/service/OAuthLoginService.java
  src/main/java/com/dnd/demo/domain/oauth/service/RequestOAuthInfoService.java
  src/main/java/com/dnd/demo/domain/oauth/service/RequestOAuthUnlinkService.java
  src/main/java/com/dnd/demo/global/auth/config/AppConfig.java
  src/main/java/com/dnd/demo/global/auth/config/SecurityConfig.java
  src/main/java/com/dnd/demo/global/auth/service/CustomUserDetailService.java
  src/main/java/com/dnd/demo/global/exception/ErrorCode.java
  src/main/resources/static/kakao_login_medium_narrow.png
  src/main/resources/templates/login.html
Labels: bug

#29 사용자 온보딩 완료 상태 값 변경 api 구현
  build.gradle
  src/main/java/com/dnd/demo/domain/member/controller/MemberController.java
  src/main/java/com/dnd/demo/domain/member/dto/request/OnboardingStatusRequest.java
  src/main/java/com/dnd/demo/domain/member/entity/Member.java
  src/main/java/com/dnd/demo/domain/member/service/MemberService.java
Labels: enhancement

#35 myPage에 카테고리 정보도 추가
  src/main/java/com/dnd/demo/domain/mypage/dto/MyPageProjectResponseDto.java
  src/main/java/com/dnd/demo/domain/mypage/service/MyPageServiceImpl.java
  src/main/java/com/dnd/demo/domain/project/dto/response/PlatformCategoryResponse.java
  src/main/java/com/dnd/demo/domain/project/repository/ProjectCategoryRepository.java
  src/main/java/com/dnd/demo/domain/project/service/ProjectCategoryService.java
Labels: bug

#36 광고 적용된 프로젝트 조회 수정
  src/main/java/com/dnd/demo/domain/advertisement/service/AdvertisementService.java
  src/main/java/com/dnd/demo/domain/project/service/ProjectService.java
  src/main/java/com/dnd/demo/global/auth/config/SecurityConfig.java
  src/main/java/com/dnd/demo/global/exception/ErrorCode.java
Labels: bug

#41 회원 검색 api 구현
  src/main/java/com/dnd/demo/domain/member/controller/MemberController.java
  src/main/java/com/dnd/demo/domain/member/dto/response/MemberSearchResponseDto.java
  src/main/java/com/dnd/demo/domain/member/repository/MemberRepository.java
  src/main/java/com/dnd/demo/domain/member/service/MemberService.java
Labels: enhancement

#43 같은 카테고리를 가진 프로젝트 전체 조회 api 구현
  src/main/java/com/dnd/demo/domain/project/controller/ProjectController.java
  src/main/java/com/dnd/demo/domain/project/dto/response/ProjectCategoryRecommendationResponseDto.java
  src/main/java/com/dnd/demo/domain/project/repository/ProjectQueryDslRepository.java
  src/main/java/com/dnd/demo/domain/project/repository/ProjectQueryDslRepositoryImpl.java
  src/main/java/com/dnd/demo/domain/project/service/ProjectCategoryService.java
  src/main/java/com/dnd/demo/domain/project/service/ProjectService.java
Labels: enhancement

#50 피드백 답변 결과 조회에 대한 응답 데이터 추가 - 질문 제목
  src/main/java/com/dnd/demo/domain/Quiz/dto/request/QuizRequest.java
  src/main/java/com/dnd/demo/domain/feedback/dto/response/FeedbackQuestionResultResponse.java
  src/main/java/com/dnd/demo/domain/feedback/dto/response/FeedbackResultResponse.java
  src/main/java/com/dnd/demo/domain/feedback/service/FeedbackResponseService.java
  src/main/java/com/dnd/demo/domain/project/dto/request/ProjectCreateRequest.java
  src/main/java/com/dnd/demo/domain/project/dto/request/ProjectDetailRequest.java
  src/main/java/com/dnd/demo/domain/project/dto/request/TemporaryProjectCreateRequest.java
Labels: bug
